name: ci

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            exit 1
          fi
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - run: go test ./...

  create_release:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: build and release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }}
  build_release:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [lint, test, create_release]
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"
      - name: build and release
        env:
          GH_TOKEN: ${{ github.token }}
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          BIN_FILE: launcher-extras
          ZIP_FILE: launcher-extras-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        run: |
          go build -o bin/${BIN_FILE}
          cd bin
          tar cvfz ${ZIP_FILE} ${BIN_FILE}
          MD5_SUM=$(md5sum ${ZIP_FILE} | cut -d ' ' -f 1)
          echo ${MD5_SUM} > ${ZIP_FILE}.md5
          gh release upload ${{ github.ref_name }} ${ZIP_FILE} ${ZIP_FILE}.md5
